import typing
from langchain_core.documents import Document
from langchain_core.messages import BaseMessage, AIMessage, ToolMessage

class AgentStateV2(typing.TypedDict):
    """
    Represents the state of the RAG Reasoning Agent V2.
    """
    user_query: str
    chat_history: typing.List[BaseMessage]
    # Storing tool calls and their outputs.
    # LangGraph typically expects AIMessage (for tool calls) and ToolMessage (for results)
    # or a list of AIMessage with tool_calls.
    intermediate_steps: typing.List[typing.Union[AIMessage, ToolMessage]]
    retrieved_documents: typing.List[Document] # Documents retrieved from vector store
    file_contents: typing.Dict[str, str] # Dictionary mapping file paths to their content
    final_answer: typing.Optional[str] # The final answer generated by the agent
