import typing

from langchain_core.documents import Document
from langchain_core.messages import BaseMessage

class AgentState(typing.TypedDict):
    """
    Represents the state of the agent at any point in the conversation.
    """
    user_query: str
    chat_history: typing.List[BaseMessage] # Can store HumanMessage, AIMessage, SystemMessage, etc.
    query_type: str # e.g., "general_qa", "file_based_qa", "retrieval_qa"
    plan: typing.List[str] # A list of steps the agent plans to take
    current_step_index: int # Index of the current step in the plan
    retrieved_documents: typing.List[Document] # Documents retrieved from vector store
    file_contents: typing.Dict[str, str] # Dictionary mapping file paths to their content
    final_answer: str # The final answer generated by the agent
    missing_info_request: str # If agent needs more info, this field will contain the request
    intermediate_steps: list # Stores intermediate tool calls and their results, e.g., [(tool_action, tool_observation), ...]
